### ISSUE TITLE
Uncaught TypeError: currentFontSize.toLowerCase is not a function

### ISSUE THREAD

**Issue by tvanantwerp** [silvestreh/atom-material-ui#127]
Attempted to change the User interface font size. This error occured immediately after beginning to type.

**Atom Version**: 1.2.4
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v1.0.1

### Stack Trace

Uncaught TypeError: currentFontSize.toLowerCase is not a function

```
At /C:/Users/tva/.atom/packages/atom-material-ui/lib/config.coffee:143

TypeError: currentFontSize.toLowerCase is not a function
    at setFontSize (file:///C:/Users/tva/.atom/packages/atom-material-ui/lib/config.coffee:1:1)
    at file:///C:/Users/tva/.atom/packages/atom-material-ui/lib/config.coffee:1:1
    at C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:588:20
    at Emitter.module.exports.Emitter.emit (C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:773:29)
    at Config.module.exports.Config.setRawValue (C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:565:19)
    at Config.module.exports.Config.set (C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:226:14)
    at SettingsPanel.module.exports.SettingsPanel.set (C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:196:28)
    at C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:242:26
    at Emitter.module.exports.Emitter.emit (C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\tva\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1276:25
```

### Commands

```
     -8:09.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -7:33.5.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
  3x -6:00.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:47.4.0 core:save (atom-text-editor.editor.is-focused)
     -4:03.1.0 core:undo (atom-text-editor.editor.is-focused)
     -3:56.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:31.6.0 core:undo (atom-text-editor.editor.is-focused)
     -3:29.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:51.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:48.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:04.0 core:backspace (atom-text-editor#atom-material-ui.fonts.fontSize.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "atom-material-ui": {
    "ui": {},
    "tabs": {},
    "fonts": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.6
atom-material-ui, v1.0.1
file-icons, v1.6.12
language-jade, v0.6.2
linter, v1.11.3
linter-csslint, v1.1.0
linter-jscs, v3.2.0
linter-pylint, v1.1.1
linter-scss-lint, v2.4.0
linter-xmllint, v1.1.0
minimap, v4.16.2
pigments, v0.19.1

# Dev
No dev packages
```

**Comment by silvestreh** [comment]
That's… strange. `/lib/config.coffee` is only 73 lines. You probably have an issue with old settings. If you don't mind, open DevTools console inside Atom and type:

`atom.config.set('atom-material-ui')`

That should reset your settings (which should've happened automatically)

**Comment by c0m3tx** [comment]
This is happening again today after update...

Uncaught TypeError: currentFontSize.toLowerCase is not a function
/home/c0m3tx/.atom/packages/atom-material-ui/lib/config.coffee:143

Already tried resetting configuration, but it didn't work.

**Comment by Thanood** [comment]
I can confirm this. Just happened after ```atom.config.set('atom-material-ui')```.

**Comment by c0m3tx** [comment]
Moreover that file doesn't seem to even exist on my computer...

**Comment by silvestreh** [comment]
I'm not exactly sure what the problem is, but looks like it might be related to cache. Try deleting `~/.atom/compile-cache` and restarting Atom. Also open your `~/config.cson` and remove all references to `atom-material-ui`.

BTW, you can change UI font size using a text input in the theme's settings.

**Comment by Thanood** [comment]
> BTW, you can change UI font size using a text input in the theme's settings.

That's what's causing the error for me. :smile: 
I'll try clearing the cache.

**Comment by sethxd** [comment]
I had the same problem today and that fix worked for me too, thanks!
