### ISSUE TITLE
Failed to activate the atom-material-ui package

### ISSUE THREAD

**Issue by webbteche** [silvestreh/atom-material-ui#133]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v1.0.3

### Stack Trace

Failed to activate the atom-material-ui package

```
At currentFontSize.toLowerCase is not a function

TypeError: currentFontSize.toLowerCase is not a function
    at setFontSize (file:///C:/Users/Webb/.atom/packages/atom-material-ui/lib/config.coffee:1:1)
    at file:///C:/Users/Webb/.atom/packages/atom-material-ui/lib/config.coffee:1:1
    at C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:588:20
    at Emitter.module.exports.Emitter.emit (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:773:29)
    at Config.module.exports.Config.transact (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:314:14)
    at Config.module.exports.Config.resetSettingsForSchemaChange (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:738:19)
    at Config.module.exports.Config.setSchema (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:374:19)
    at ThemePackage.module.exports.Package.activateConfig (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:192:23)
    at ThemePackage.module.exports.Package.activateNow (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:166:14)
    at C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\theme-package.js:45:28
    at ThemePackage.module.exports.Package.measure (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:92:15)
    at C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\theme-package.js:41:24
    at ThemePackage.module.exports.ThemePackage.activate (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\theme-package.js:37:97)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:512:21)
    at C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:385:60
    at exit (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Webb\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -8:42.2.0 core:save (atom-text-editor.editor.is-focused)
     -8:32 core:paste (atom-text-editor.editor.is-focused)
  2x -8:31.2.0 core:save (atom-text-editor.editor.is-focused)
     -8:22.4.0 core:paste (atom-text-editor.editor.is-focused)
     -8:21.3.0 core:save (atom-text-editor.editor.is-focused)
     -8:11.8.0 core:paste (atom-text-editor.editor.is-focused)
     -8:11 core:save (atom-text-editor.editor.is-focused)
     -7:55.4.0 core:paste (atom-text-editor.editor.is-focused)
     -7:54.4.0 core:save (atom-text-editor.editor.is-focused)
     -7:44.9.0 core:paste (atom-text-editor.editor.is-focused)
     -7:44.1.0 core:save (atom-text-editor.editor.is-focused)
     -5:39.1.0 settings-view:show-keybindings (atom-text-editor.editor.is-focused)
     -5:29.4.0 settings-view:open (atom-text-editor.editor.is-focused)
  4x -3:44.5.0 window:toggle-full-screen (input#core.autoHideMenuBar.)
     -0:45.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.0.3
auto-indent, v0.5.0
color-picker, v2.0.13

# Dev
No dev packages
```

**Comment by silvestreh** [comment]
cache maybe? the fontsize feature is no longer there.

**Comment by btleffler** [comment]
Uninstalling and reinstalling `atom-material-ui` seems to have resolved this issue for me.

Windows 10
Atom 1.2.4

**Comment by webbteche** [comment]
Well I rerun the application and I update it again.
Now it works fine, maybe just atom bugs
Sorry for bad english. :)
