### ISSUE TITLE
Error with ui

### ISSUE THREAD

**Issue by iamjstates** [silvestreh/atom-material-ui#220]
I'm using Atom 1.5.3 and the Beta release. Every time I install this package I get the following error when loading a new window - or reloading the application.
`Error
    at new Parser (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:281:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:232:19)
    at new AtomEnvironment (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:250:19)
    at module.exports (/Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:19:19)
    at setupWindow (file:///Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Misc/Editors/Atom/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)`

**Comment by silvestreh** [comment]
There's no beta. It's been released two days ago. I recommend reinstalling from APM (or if you want to keep using the development version, just pull from the repo).

That said, the error you're getting is a bug with settings-view where it sometimes returns an invalid HEX color. There's nothing I can do about it, except filing a bug report with them ([which I already did](https://github.com/atom/settings-view/issues/712)).

If you'd like, you can run this in a dev console to reset the colors back to default

```javascript
atom.config.set('atom-material-ui.colors');
```

Also, try to avoid picking very dark colors as those are the ones that seem to trigger this bug. Saturated pink-ish colors also produce badly formatted HEX colors.

**Comment by silvestreh** [comment]
BTW, I refactored the code to avoid saving a bad HEX color and, when an invalid HEX is generated, revert to previous value. That way you won't get the same behavior and a nice notification will show letting you know that `settings-view` returned an invalid color.
